# Welcome to Jekyll!
#

# Site settings
title: Lucía Güitta López
description: |
  Electronics Engineer - Ph.D. candidate
owner: Lucía Güitta López # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: lucia.guitta@iit.comillas.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lucia-guitta.github.io" # the base hostname & protocol for your site
social:
  linkedin: https://linkedin.com/in/lucía-güitta-lópez-081962122/
  orcid-square: https://orcid.org/0000-0003-2426-3748
  google-scholar-square: https://scholar.google.es/citations?user=We9MhRcAAAAJ&hl=es&oi=ao
  researchgate-square: https://www.researchgate.net/profile/Lucia-Gueitta-Lopez
  instagram: https://www.instagram.com/luu_gl/
  envelope: mailto:lucia.guitta@iit.comillas.edu

# Build settings
markdown: kramdown
#sass:
#  style: compressed
